"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function selectApplicantRole() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in");

  const admin = createAdminClient();

  // Create JB role
  await admin
    .from("jb_user_roles")
    .upsert(
      { user_id: user.id, role: "applicant" as const },
      { onConflict: "user_id,role", ignoreDuplicates: true }
    );

  // Create empty applicant profile (anonymous_id auto-generated by trigger)
  await admin
    .from("jb_applicant_profiles")
    .upsert(
      { user_id: user.id, anonymous_id: "" },
      { onConflict: "user_id", ignoreDuplicates: true }
    );

  redirect("/jobs/profile");
}

export async function selectCompanyRole() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/sign-in");

  const admin = createAdminClient();

  // Create JB role
  await admin
    .from("jb_user_roles")
    .upsert(
      { user_id: user.id, role: "company_member" as const },
      { onConflict: "user_id,role", ignoreDuplicates: true }
    );

  // Create company
  const { data: company } = await admin
    .from("jb_companies")
    .insert({ name: "My Company" })
    .select("id")
    .single();

  if (company) {
    await admin
      .from("jb_company_members")
      .insert({ company_id: company.id, user_id: user.id, is_owner: true });
  }

  redirect("/jobs/company-profile");
}
